package main

import "fmt"

type MyString string

func (m MyString) String() string {
	return fmt.Sprintf("MyString=%s", m) // 错误：会无限递归
}

//./12.14_print_error.go:8 +0xd2 fp=0xc020167a30 sp=0xc0201679a0 pc=0x496492
//main.(*MyString).String(0xc0073271a0)
//<autogenerated>:1 +0x4f fp=0xc020167a80 sp=0xc020167a30 pc=0x4965ef
//fmt.(*pp).handleMethods(0xc0073385b0, 0x73)
///snap/go/8779/src/fmt/print.go:626 +0xb92 fp=0xc020167dd0 sp=0xc020167a80 pc=0x491eb2
//fmt.(*pp).printArg(0xc0073385b0, {0x49fb60, 0xc0073271a0}, 0x73)
///snap/go/8779/src/fmt/print.go:709 +0xc65 fp=0xc020167f40 sp=0xc020167dd0 pc=0x492e65
//fmt.(*pp).doPrintf(0xc0073385b0, {0x4ada3a, 0xb}, {0xc0201681b0, 0x1, 0x1})
///snap/go/8779/src/fmt/print.go:1026 +0x6fa fp=0xc0201680d8 sp=0xc020167f40 pc=0x49575a
//...additional frames elided...
//

func main() {
	s := MyString("SSSSString")
	fmt.Println(s)
}
